version: '3.2'
services:
 elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
  volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
  ports:
      - "9200:9200"
      - "9300:9300"
  environment:
       ES_JAVA_OPTS: "-Xmx256m -Xms256m"
       ELASTIC_PASSWORD: changeme
       discovery.type: single-node
  networks:
      - elk
      
 kibana:
  image: docker.elastic.co/kibana/kibana:7.8.0
  volumes:
     - type: bind
       source: ./kibana/config/kibana.yml
       target: /usr/share/kibana/config/kibana.yml
       read_only: true
  ports:
      - "5601:5601"
  networks:
      - elk
  depends_on:
      - elasticsearch


 nginx:
  image: nginx:alpine
  volumes:
         - ./nginx/config:/etc/nginx/conf.d
         - ./nginx/multipurpose:/usr/share/nginx/html 
         - /var/log/nginx:/var/log/nginx 
  ports:
      - "80:80"
  networks:
      - elk
  

 filebeat:
  image: docker.elastic.co/beats/filebeat:7.8.0
  user: root
  entrypoint: "filebeat -e -strict.perms=false"
  volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/log/nginx:/var/log/nginx
      - /var/run/docker.sock:/var/run/docker.sock:ro
  networks:
      - elk
  links:
      - nginx

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
  
